import type { Property, PropertyType, SearchFilters } from '../types';
import { log } from './httpDefaults';

const BASE_URL = 'https://api.rentcast.io/v1'; const DEFAULT_LIMIT = 50; const MAX_LIMIT = 100;
let consecutiveFailures = 0; let circuitOpenUntil = 0;
interface RentCastRecord { id?: string | number; addressLine1?: string; addressLine2?: string; city?: string; state?: string; zipCode?: string; subdivision?: string; latitude?: number; longitude?: number; propertyType?: string; bedrooms?: number; bathrooms?: number; squareFootage?: number; lotSize?: number; yearBuilt?: number; price?: number; lastSalePrice?: number; lastSaleDate?: string; listedDate?: string; createdDate?: string; daysOnMarket?: number; listingType?: string; mlsName?: string; mlsNumber?: string; features?: Record<string, unknown>; hoa?: { fee?: number }; history?: Record<string, { price?: number; date?: string; listedDate?: string }>; taxAssessments?: Record<string, { value?: number; land?: number; improvements?: number }>; propertyTaxes?: Record<string, { total?: number }>; listingOffice?: { name?: string }; }
interface RentCastAvm { price?: number; priceRangeLow?: number; priceRangeHigh?: number; rent?: number; rentRangeLow?: number; rentRangeHigh?: number; }

export class RentCastProviderError extends Error { constructor(message: string, public readonly statusCode = 502) { super(message); this.name = 'RentCastProviderError'; } }
export const isRentCastConfigured = () => Boolean(process.env.RENTCAST_API_KEY?.trim());
const key = () => { const value = process.env.RENTCAST_API_KEY?.trim(); if (!value) throw new RentCastProviderError('RENTCAST_API_KEY is not configured.', 503); return value; };
const string = (value: unknown, name: string, max = 100) => { const text = String(value ?? '').trim(); if (text.length > max) throw new RentCastProviderError(`${name} must be ${max} characters or fewer.`, 400); return text; };

async function rentCastGet<T>(path: string, query: URLSearchParams): Promise<T> {
  if (Date.now() < circuitOpenUntil) throw new RentCastProviderError('RentCast is temporarily unavailable; retry shortly.', 503);
  try {
    const response = await fetch(`${BASE_URL}${path}?${query}`, { headers: { Accept: 'application/json', 'X-Api-Key': key(), 'User-Agent': 'kc-real-estate-market-explorer/1.0' }, signal: AbortSignal.timeout(8_000) });
    if (!response.ok) { const message = response.status === 401 ? 'RentCast rejected the API key or subscription.' : response.status === 429 ? 'RentCast rate limit exceeded.' : `RentCast request failed with HTTP ${response.status}.`; throw new RentCastProviderError(message, response.status === 429 ? 429 : 502); }
    consecutiveFailures = 0; return await response.json() as T;
  } catch (error) {
    if (error instanceof RentCastProviderError && error.statusCode === 400) throw error;
    consecutiveFailures++; if (consecutiveFailures >= 3) circuitOpenUntil = Date.now() + 30_000;
    const timedOut = error instanceof DOMException && error.name === 'TimeoutError';
    const providerError = error instanceof RentCastProviderError ? error : new RentCastProviderError(timedOut ? 'RentCast request timed out.' : 'RentCast request failed.', timedOut ? 504 : 502);
    log('warn', 'rentcast_request_failed', { status: providerError.statusCode, failures: consecutiveFailures }); throw providerError;
  }
}
function type(value: unknown): PropertyType { const v = String(value || '').toLowerCase(); return v.includes('condo') ? 'condo' : v.includes('town') ? 'townhouse' : v.includes('multi') || v.includes('apartment') ? 'multi_family' : v.includes('manufactured') || v.includes('mobile') ? 'manufactured' : v.includes('land') ? 'land' : 'single_family'; }
function location(params: Record<string, unknown>) { const filters = params.filters as SearchFilters | undefined; const raw = string(params.zipCode || filters?.zipCode || params.location || filters?.locationQuery, 'location'); const zipCode = raw.match(/\b\d{5}\b/)?.[0]; if (zipCode) return { zipCode }; const primary = raw.split('/')[0].trim(); const match = primary.match(/^(.+?)[,\s]+([A-Za-z]{2})$/); if (!match) throw new RentCastProviderError('Use a city/state or 5-digit ZIP code for live searches.', 400); return { city: string(match[1], 'city'), state: string(match[2], 'state', 2).toUpperCase() }; }
function addLocation(query: URLSearchParams, params: Record<string, unknown>) { const parsed = location(params); Object.entries(parsed).forEach(([name, value]) => query.set(name, value)); }
function range(min?: number, max?: number) { return min == null && max == null ? undefined : `${min ?? '*'}:${max ?? '*'}`; }
function filters(query: URLSearchParams, value?: SearchFilters, includePrice = false) { if (!value) return; const types = value.propertyTypes?.map(t => ({ single_family: 'Single Family', condo: 'Condo', townhouse: 'Townhouse', multi_family: 'Multi-Family', manufactured: 'Manufactured', land: 'Land' })[t]).filter(Boolean).join('|'); const fields: [string, string | undefined][] = [['propertyType', types], ['bedrooms', range(value.minBeds, value.maxBeds)], ['bathrooms', range(value.minBaths, value.maxBaths)], ['squareFootage', range(value.minSqft, value.maxSqft)], ['lotSize', range(value.minLotSqft, value.maxLotSqft)], ['yearBuilt', range(value.minYearBuilt, value.maxYearBuilt)], ['price', includePrice ? range(value.minPrice, value.maxPrice) : undefined]]; fields.forEach(([name, value]) => { if (value) query.set(name, value); }); }
function base(record: RentCastRecord): Omit<Property, 'price'|'status'|'pricePerSqFt'|'daysOnMarket'|'dateListed'|'priceReduced'|'images'|'priceHistory'|'description'> { const street = [record.addressLine1, record.addressLine2].filter(Boolean).join(', ') || 'Address unavailable'; const assessments = record.taxAssessments || {}; const taxes = record.propertyTaxes || {}; return { id: String(record.id || ''), zpid: String(record.id || ''), address: { street, city: record.city || '', state: record.state || '', zipCode: record.zipCode || '', neighborhood: record.subdivision, lat: Number(record.latitude || 0), lng: Number(record.longitude || 0) }, propertyType: type(record.propertyType), bedrooms: Number(record.bedrooms || 0), bathrooms: Number(record.bathrooms || 0), livingAreaSqFt: Number(record.squareFootage || 0), lotSizeSqFt: Number(record.lotSize || 0), yearBuilt: Number(record.yearBuilt || 0), originalPrice: undefined, lastSoldPrice: undefined, lastSoldDate: undefined, zestimate: undefined, rentZestimate: undefined, hoaFee: record.hoa?.fee, priceReductionAmount: undefined, priceReductionDate: undefined, features: { garage: Boolean(record.features?.garage), pool: Boolean(record.features?.pool) }, taxHistory: [...new Set([...Object.keys(assessments), ...Object.keys(taxes)])].map(year => ({ year: Number(year), propertyTaxes: Number(taxes[year]?.total || 0), taxAssessmentValue: Number(assessments[year]?.value || 0), assessmentLand: assessments[year]?.land, assessmentImprovement: assessments[year]?.improvements })).filter(v => Number.isFinite(v.year)), nearbySchools: [], sourceAttribution: `RentCast API${record.mlsName ? ` · ${record.mlsName}` : ''}`, retrievedAt: new Date().toISOString(), isMockData: false }; }
function listing(record: RentCastRecord): Property { const price = Number(record.price || 0); const history = Object.entries(record.history || {}).map(([date, item]) => ({ date: item.listedDate || date, event: 'Listed' as const, price: Number(item.price || 0), source: 'RentCast API' })).filter(v => v.price); const originalPrice = history[0]?.price || price; return { ...base(record), price, originalPrice, status: String(record.listingType).toLowerCase() === 'foreclosure' ? 'foreclosure' : 'for_sale', pricePerSqFt: record.squareFootage ? Math.round(price / record.squareFootage) : 0, daysOnMarket: Number(record.daysOnMarket || 0), dateListed: record.listedDate || record.createdDate || new Date().toISOString(), priceReduced: originalPrice > price, priceReductionAmount: originalPrice > price ? originalPrice - price : undefined, images: [], priceHistory: history, description: 'Live sale listing retrieved from RentCast.' }; }
function sold(record: RentCastRecord): Property { const price = Number(record.lastSalePrice || 0); return { ...base(record), price, lastSoldPrice: price || undefined, lastSoldDate: record.lastSaleDate, status: 'recently_sold', pricePerSqFt: record.squareFootage ? Math.round(price / record.squareFootage) : 0, daysOnMarket: 0, dateListed: record.lastSaleDate || new Date().toISOString(), priceReduced: false, images: [], priceHistory: [], description: 'Recent sale record retrieved from RentCast public records.' }; }
async function search(params: Record<string, unknown>) { const activeFilters = params.filters as SearchFilters | undefined; const statuses = activeFilters?.status?.length ? activeFilters.status : ['for_sale']; const limit = Math.min(MAX_LIMIT, Math.max(1, Number(params.limit || DEFAULT_LIMIT))); const offset = Math.max(0, Number(params.offset || 0)); const output: Property[] = []; const limitations: string[] = [];
  if (statuses.some(status => status === 'for_sale' || status === 'foreclosure')) { const query = new URLSearchParams({ status: 'Active', limit: String(limit), offset: String(offset) }); addLocation(query, params); filters(query, activeFilters, true); (await rentCastGet<RentCastRecord[]>('/listings/sale', query)).forEach(record => output.push(listing(record))); }
  if (statuses.includes('recently_sold')) { const query = new URLSearchParams({ limit: String(limit), offset: String(offset) }); addLocation(query, params); filters(query, activeFilters); (await rentCastGet<RentCastRecord[]>('/properties', query)).filter(record => record.lastSalePrice && record.lastSaleDate).forEach(record => output.push(sold(record))); }
  if (statuses.includes('pending')) limitations.push('Pending listings require a licensed MLS/RESO provider and are not returned by this adapter.'); const properties = [...new Map(output.map(item => [item.id, item])).values()].slice(0, limit); return { totalReturned: properties.length, properties, hasMore: properties.length === limit, nextOffset: properties.length === limit ? offset + limit : null, query: String(params.location || activeFilters?.locationQuery || 'Live search'), provider: 'rentcast', limitations }; }
async function avm(params: Record<string, unknown>) { const query = new URLSearchParams(); const id = String(params.propertyId || params.zpid || '').trim(); if (id) query.set('propertyId', id); else addLocation(query, params); const result = await rentCastGet<RentCastAvm>('/avm/value', query); return { price: Number(result.price || 0), priceRangeLow: Number(result.priceRangeLow || 0), priceRangeHigh: Number(result.priceRangeHigh || 0), rent: Number(result.rent || 0), rentRangeLow: Number(result.rentRangeLow || 0), rentRangeHigh: Number(result.rentRangeHigh || 0) }; }
export async function executeRentCastTool(toolName: string, params: Record<string, unknown> = {}) { switch (toolName) { case 'zillow_search': return search(params); case 'zillow_property_details': { const id = string(params.propertyId || params.zpid, 'propertyId'); if (!id) throw new RentCastProviderError('propertyId is required.', 400); return sold(await rentCastGet<RentCastRecord>(`/properties/${encodeURIComponent(id)}`, new URLSearchParams())); } case 'zillow_market_trends': { const parsed = location(params); if (!parsed.zipCode) throw new RentCastProviderError('RentCast market statistics require a 5-digit ZIP code.', 400); return rentCastGet('/markets', new URLSearchParams({ zipCode: parsed.zipCode, dataType: 'Sale', historyRange: '12' })); } case 'zillow_zestimate': return avm(params); case 'zillow_comparables': throw new RentCastProviderError('Comparable scoring is calculated client-side from returned properties.', 400); default: throw new RentCastProviderError(`Unsupported real-estate tool: ${toolName}`, 400); } }
