import React, { useState } from 'react';
import { AlertTriangle, BrainCircuit, Calculator, CheckCircle2, RefreshCw } from 'lucide-react';
import { DeploymentMode } from '../config/runtime';
import { MarketInsightResponse, MarketSummary } from '../types';

interface InsightPanelProps {
  insights: MarketInsightResponse | null;
  summary: MarketSummary;
  searchRegion: string;
  onRefreshInsights: () => void;
  isLoading: boolean;
  deploymentMode: DeploymentMode;
}

type InsightTab = 'facts' | 'calculated' | 'interpretations' | 'unavailable';

export const InsightPanel: React.FC<InsightPanelProps> = ({ insights, summary, searchRegion, onRefreshInsights, isLoading, deploymentMode }) => {
  const [activeTab, setActiveTab] = useState<InsightTab>('facts');
  const isLocal = deploymentMode === 'static' || !insights?.isAiGenerated;
  const tabs: Array<{ id: InsightTab; label: string; icon: React.ReactNode; items: string[] }> = [
    { id: 'facts', label: 'Dataset facts', icon: <CheckCircle2 className="h-4 w-4" />, items: insights?.verifiedFacts || [] },
    { id: 'calculated', label: 'Calculated', icon: <Calculator className="h-4 w-4" />, items: insights?.calculatedMetrics || [] },
    { id: 'interpretations', label: 'Interpretation', icon: <BrainCircuit className="h-4 w-4" />, items: insights?.aiInterpretations || [] },
    { id: 'unavailable', label: 'Unavailable', icon: <AlertTriangle className="h-4 w-4" />, items: insights?.missingDataNotes || [] },
  ];
  const activeItems = tabs.find(tab => tab.id === activeTab)?.items || [];

  return (
    <div className="w-full overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-[#230b42] via-[#2f0e52] to-[#17062e] p-5 text-white shadow-xl sm:p-6">
      <div className="flex flex-col gap-4">
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="mb-1 inline-flex rounded-full border border-purple-300/20 bg-white/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-purple-100">
              {isLocal ? 'Local Market Analysis' : 'Gemini Market Insights'}
            </div>
            <h2 className="text-lg font-bold sm:text-xl">{searchRegion || 'Kansas City Metro'}</h2>
            <p className="mt-1 text-xs text-purple-200/80">
              {isLocal ? 'Derived locally from the current fixture dataset.' : 'Generated by the configured server-side Gemini integration.'}
            </p>
          </div>
          <button type="button" onClick={onRefreshInsights} disabled={isLoading} className="flex shrink-0 items-center gap-1.5 rounded-xl border border-white/10 bg-white/10 px-3 py-2 text-xs font-semibold text-purple-100 transition hover:bg-white/20 disabled:opacity-50" aria-label="Refresh market analysis">
            <RefreshCw className={`h-3.5 w-3.5 ${isLoading ? 'animate-spin' : ''}`} />
            {isLoading ? 'Analyzing' : 'Refresh'}
          </button>
        </div>

        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          <Metric label="Properties" value={summary.totalProperties.toLocaleString()} />
          <Metric label="Median price" value={summary.medianListingPrice ? `$${summary.medianListingPrice.toLocaleString()}` : '—'} />
          <Metric label="Median $/sq ft" value={summary.medianPricePerSqFt ? `$${summary.medianPricePerSqFt}` : '—'} />
          <Metric label="Avg. days listed" value={summary.avgDaysOnMarket ? `${summary.avgDaysOnMarket}` : '—'} />
        </div>

        <p className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-relaxed text-purple-50">
          {insights?.executiveSummary || 'Preparing a market snapshot from the current filtered dataset…'}
        </p>

        <div className="flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Market analysis categories">
          {tabs.map(tab => (
            <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`flex min-h-10 shrink-0 items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-semibold transition ${activeTab === tab.id ? 'bg-white text-purple-950' : 'bg-white/10 text-purple-100 hover:bg-white/20'}`}>
              {tab.icon}{tab.label}
            </button>
          ))}
        </div>

        <div role="tabpanel" className="rounded-2xl border border-white/10 bg-black/10 p-4">
          {activeItems.length > 0 ? (
            <ul className="space-y-2 text-xs leading-relaxed text-purple-50 sm:text-sm">
              {activeItems.map(item => <li key={item} className="flex gap-2"><span aria-hidden="true">•</span><span>{item}</span></li>)}
            </ul>
          ) : <p className="text-xs text-purple-200">No information is available for this category.</p>}
        </div>
      </div>
    </div>
  );
};

const Metric: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="rounded-2xl border border-white/10 bg-white/10 p-3 text-center">
    <div className="text-sm font-extrabold sm:text-base">{value}</div>
    <div className="mt-1 text-[10px] font-medium text-purple-200 sm:text-xs">{label}</div>
  </div>
);
